version: "3"

services:
  mongodb:
    image: mongo:6
    restart: always
    container_name: mongodb
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--wiredTigerCacheSizeGB",
        "1",
      ]

volumes:
  mongodata:
